ProductBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: ProductBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '35'
        creationDate:
            type: datetime
        editionDate:
            type: datetime
    lifecycleCallbacks: {  }
