product_products:
    resource: "@ProductBundle/Resources/config/routing/product.yml"
    prefix:   /products

product_categories:
    resource: "@ProductBundle/Resources/config/routing/category.yml"
    prefix:   /category

product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Default:homepage }
