<?php

namespace PentalogUserBundle\Repository;

/**
 * PentalogUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PentalogUserRepository extends \Doctrine\ORM\EntityRepository
{
}
