categories_index:
    path:     /
    defaults: { _controller: "ProductBundle:Category:index" }
    methods:  GET

categories_show:
    path:     /{id}/show
    defaults: { _controller: "ProductBundle:Category:show" }
    methods:  GET

categories_new:
    path:     /new
    defaults: { _controller: "ProductBundle:Category:new" }
    methods:  [GET, POST]

categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductBundle:Category:edit" }
    methods:  [GET, POST]

categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductBundle:Category:delete" }
    methods:  DELETE
